### ISSUE TITLE
Change Deleted Flag to Active

### ISSUE THREAD

**Issue by divsmith** [jantaylor/road-home-time-tracker#107]
The models currently have a deleted flag that is set by default to false and gets set to true if that object is deleted. Because it's set to false when they're active, the admin page shows a negative red picture. For better user experience I think this should be changed to an active flag that shows a green checkmark instead.
![screenshot from 2017-07-06 17-01-12](https://user-images.githubusercontent.com/3256015/27936183-bcb6384c-626c-11e7-81a6-0547b19463bd.png)

**Comment by jantaylor** [comment]
Was completed in PR #108
