### ISSUE TITLE
Report of volunteers last volunteer date > 6 months

### ISSUE THREAD

**Issue by jantaylor** [jantaylor/road-home-time-tracker#136]
Either a report or a command that deactivates volunteers that haven't volunteered in 6 months.
After talking to Adam on Monday, they have about 50 volunteers a day and big events, up to 400 volunteers. For logging in and long term sanity, we should help them clear out volunteers who aren't volunteering anymore. They can re-activate the account or re-add them and it's still a unique volunteer entry.

**Comment by CadenMo33** [comment]
Finished
