### ISSUE TITLE
storyboard index view

### ISSUE THREAD

**Issue by divsmith** [jantaylor/road-home-time-tracker#24]
Draw and diagram index view

**Comment by divsmith** [comment]
This might have a list of current volunteers to search from and a simple form to add a new volunteer if they aren't found.

**Comment by jantaylor** [comment]
The list will be generated from a SQL query on the volunteer table.

**Comment by CadenMo33** [comment]
![indexstoryboard](https://user-images.githubusercontent.com/28583057/27150206-879ab4a0-5103-11e7-8af7-a1be64faddea.jpg)

Here is a rough sketch for the index view. 

The search bar will be below the alphabet. We could also move the alphabet down the side of the names.

**Comment by jantaylor** [comment]
Index looks just like storyboard view. Great job.
