### ISSUE TITLE
Hide Django admin next url

### ISSUE THREAD

**Issue by jantaylor** [jantaylor/road-home-time-tracker#29]
Django next parameter shows in the URL, it'd be nice to hide this for security.

admin/login/?next=/admin/ should just be admin/ or admin/login

**Comment by dabidpoto** [comment]
@jantaylor I have been looking high and low to figure this one out, it looks like it may have to stay that way because of the way admin is built in the app, it changes based on login and logout.

**Comment by jantaylor** [comment]
@dabidpoto My friend has his hidden. I wonder if he's using apache or IIS to hide it.

**Comment by jantaylor** [comment]
No need to complete.
