### ISSUE TITLE
Create New Volunteer Hour Entry

### ISSUE THREAD

**Issue by jantaylor** [jantaylor/road-home-time-tracker#3]
A user can login, upon logging in, enter the date and hours they worked from

**Comment by divsmith** [comment]
Adam has said that he wants the timestamping function, i.e. just a 'Check In' / 'Check Out' button for a volunteer that records the current time. The manual time/date entry should be on the admin backend.

**Comment by jantaylor** [comment]
So the timestamping function. Can you or Adam clarify. What sort of details are required for the timestamp to work? Obviously we need a record to record the time in. Does he want the exact time in and time out and then we factor and update the hours and minutes spent?
