### ISSUE TITLE
Generate Reports

### ISSUE THREAD

**Issue by jantaylor** [jantaylor/road-home-time-tracker#8]
An admin can visit a page like /reports and view a big list of all the records.
Future updates could include filters on user, day, and supervisor.

**Comment by CadenMo33** [comment]
@jantaylor Should this be part of different sprint than sprint 1? It seems pretty early to get reports made. We should try and get the main application running.

**Comment by jantaylor** [comment]
@CadenMo33 Is the sprint due Tuesday or is it due later? If it's Tuesday, we can remove this as we haven't finalized the model.

**Comment by CadenMo33** [comment]
@jantaylor It's due the 20th. So yes on Tuesday.

**Comment by jantaylor** [comment]
@CadenMo33 I moved this to the product backlog for sprint 2.

**Comment by jantaylor** [comment]
Completed in PR #128
