### ISSUE TITLE
Add date_added and date_updated to volunteer model

### ISSUE THREAD

**Issue by jantaylor** [jantaylor/road-home-time-tracker#81]
We need to know when users are added to the system for reports and other functionality.
We also need to know the last time a record was changed.

Please add a timestamp that isn't editable that records the date_added. It should default to the current datetime when an object is created.
date_updated is a timestamp, but has to be editable. It will be updated each time a record is updated. This may have be programmed in python.

**Comment by CadenMo33** [comment]
class DateField(auto_now=False, auto_now_add=False, **options)[fuente]¶
A date, represented in Python by a datetime.date instance. Has a few extra, optional arguments:

DateField.auto_now¶
Automatically set the field to now every time the object is saved. Useful for «last-modified» timestamps. Note that the current date is always used; it’s not just a default value that you can override.

The field is only automatically updated when calling Model.save(). The field isn’t updated when making updates to other fields in other ways such as QuerySet.update(), though you can specify a custom value for the field in an update like that.

DateField.auto_now_add¶
Automatically set the field to now when the object is first created. Useful for creation of timestamps. Note that the current date is always used; it’s not just a default value that you can override. So even if you set a value for this field when creating the object, it will be ignored.
